language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "yuwangi"
- git config --global user.email "343046650@qq.com"
- npm install -g hexo-cli
- export HEXO_DEPLOYER_REPO=https://$REPO_TOKEN@github.com/yuwangi/yuwangi.github.io.git
install:
- npm i
script:
- hexo clean
- hexo generate
- hexo deploy
